Expenze/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Main/',include('Main.urls')),
    url(r'^accounts/',include('registration.backends.hmac.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/urls.py
from django.conf.urls import url
from django.contrib import admin
from Main import views
app_name ='Main'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^home/$',views.login_user,name='home'),
    url(r'^register_user/$',views.register_user,name='register_user'),
    url(r'^home_page/$',views.home_page,name='home_page'),
    url(r'^save/$',views.save,name='save'),
    url(r'^loginpage/$',views.loginpage,name='loginpage'),
    url(r'^exp_form/$',views.exp_form,name='exp_form'),
    url(r'^logout/$',views.log_out,name='logout'),
    url(r'^addexpense/$',views.addexpense,name='addexpense'),
    url(r'^chart/$',views.getExpense,name='getExpense'),
    url(r'^delete/(?P<ex_id>\d+)$',views.delete,name='delete'),
    url(r'^transactions/$',views.showtransactions,name='transactions'),
    url(r'^addloanpremium/$', views.addloanpremium, name='addloanpremium'),
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^editprofile/$', views.editprofile, name='editprofile'),
    url(r'^update/(?P<ex_id>\d+)$',views.update,name='update'),
    url(r'^lptransaction/$', views.transactions, name='trans'),
    url(r'^lpfilter/$', views.lpfilter, name='lpfilter'),
    url(r'^chart2/$',views.getExpense2,name='getExpense2'),
    url(r'^loan_form/$',views.loan_form,name='loan_form'),
    url(r'^delete_user/(?P<u_id>\d+)$', views.delete_user, name='delete_user'),
    url(r'^pdf',views.pdf,name="pdf"),

]

Main/models.py
from django.db import models
import datetime
from django.contrib.auth.models import Permission, User
from django.core.validators import RegexValidator
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator,MaxValueValidator


class Main():
    phone_regex = RegexValidator(regex=r'^\+?1?\d{10}$', message="Numeric Field. Only 10 digits allowed.")

    exp_paid = (
        ('Bank','Bank'),
        ('Cash','Cash'),
        ('CreditCard','CreditCard')
               )
    exp_types =(
            ('ATM','ATM'),
            ('Entertainment','Entertainment'),
            ('groceries','groceries'),
            ('clothing','clothing'),
            ('recharge','recharge'),
            ('Bill','Bill'),
            ('others','others'),
                )
    inc_types =(
        ('Cash','Cash'),
        ('Bonus','Bonus'),
        ('Prize','Prize'),
               )


    debit_regex = RegexValidator(regex=r'^\+?1?\d{12}$', message="Numeric Field. Only 12 digits allowed.")


class UserDetails(models.Model):
    user = models.OneToOneField(User, default=1)
    #flag =models.IntegerField(default=0)

   # savings_per_year = models.PositiveIntegerField(default=10000)
    company_name=models.CharField(max_length=100)
    dob =models.DateField(null=True)
    address =models.CharField(max_length=100)
    hire_date =models.DateField(null=True)
    phone_no = models.IntegerField()
    photo =models.ImageField(upload_to='profile',default='\static\Main\images\noimage.png')
    occupation = models.CharField(max_length=15)
    yearly_package = models.PositiveIntegerField(null=True)
    pf = models.PositiveIntegerField(default=5)
    res_address = models.CharField(max_length=100)
    def __str__(self):
        return str(self.user)

class Balance(models.Model):
    user =models.OneToOneField(User,default=1)
    expense = models.FloatField(default=0)
    income = models.FloatField(default=0)
    total =models.FloatField(default=0)
  #  tax=models.FloatField(null=True)



    def __str__(self):
         return str(self.user)


class LoanPremium(models.Model,Main):
    user = models.ForeignKey(User, default=1)
    loan_premium_name = models.CharField(max_length=50,null=True)
    loan_premium_amount = models.PositiveIntegerField(null=True)
    start_date = models.DateField(null=True)
    end_date = models.DateField(default=2017-10-3,null=True)
    #vat_id=models.CharField(max_length=20,null=True)
    description=models.CharField(max_length=200,null=True)
    no_of_years = models.IntegerField(default=20,null=True)
    #date_of_payment = models.DateField(default=timezone.now)
    rate_of_interest = models.FloatField(default=10.0,null=True)
    type_loan_premium=models.CharField(max_length=15,null=True)
    type_duration = models.CharField(max_length=15,null=True)
    is_calender = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user) + "__" + self.option + "__" + str(self.cost)

class Expense(models.Model):
    user = models.ForeignKey(User)
    subcategories = models.CharField(max_length=15)
    source = models.CharField(max_length=15)
    paid_to = models.CharField(max_length=50)
    cost = models.IntegerField()
    tax_details = models.FloatField()
    date_created = models.DateField(default =timezone.now)
    bill = models.FileField(null=True,blank=True,upload_to='bills')
    vat = models.CharField(max_length=50,null=True,blank=True)
    ext_ref = models.CharField(max_length=10,null=True,blank=True)
    description =models.CharField(max_length=100,null=True,blank=True)
    is_recurrent = models.CharField(max_length=10)
    rec_date=models.DateField(default=timezone.now)
    rec_year=models.IntegerField(null=True,blank=True)
    rec_month = models.IntegerField(null=True,blank=True)
    rec_day =models.IntegerField(null=True,blank=True)
    option = models.CharField(max_length=15)

    def __str__(self):
        return str(self.user)+"__"+self.option+"__"+str(self.cost)

Main/forms.py
from django.contrib.auth.models import User
from django import forms
from django.utils.translation import ugettext_lazy as _

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','first_name','last_name', 'email', 'password']


class Expform(forms.ModelForm):
    paid_to=forms.RegexField(regex='^\w+$',widget=forms.TextInput(attrs=dict(required=True, max_length=30)),
                             label=_("paid_to"),
                             error_message={'invalid':_("This field only contains letters, numbers or underscore.")})\

Main/views.py
from __future__ import print_function
import argparse
from reportlab.pdfgen import canvas

from googleapiclient.discovery import build
from httplib2 import Http

from oauth2client import file, client, tools
import webbrowser
from chartit.templatetags import chartit
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.shortcuts import render, redirect, render_to_response
from django.template import loader,RequestContext
from chartit import DataPool,Chart
from django.db.models.query import RawQuerySet
from django.db import connection
import simplejson
import json
from django.db.models import F,Sum,Q,aggregates, Count

from googleapiclient.discovery import build
from httplib2 import Http
import time
import argparse
import django.core.urlresolvers
from oauth2client.client import flow_from_clientsecrets
import oauth2client
from oauth2client import file, client, tools
import webbrowser
from chartit.templatetags import chartit
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.shortcuts import render, redirect, render_to_response,HttpResponseRedirect
from django.template import loader,RequestContext
from chartit import DataPool,Chart,PivotChart,PivotDataPool
import simplejson
import json,os
#from Main import client_secrets.json
from django.db.models import Aggregate
import argparse,httplib2
from oauth2client.tools import run_flow
import django_ipython
import ipython_genutils

# Create your views here.


from Main.forms import UserForm
from Main.models import Expense,Balance, UserDetails,User,LoanPremium

CLIENT_SECRETS = os.path.join(os.path.dirname(__file__), '..', 'client_secrets.json')
REDIRECT_URI = 'http://127.0.0.1:8000/Main/addloanpremium/'


def index(request):
    return render_to_response('Main/intro.html', locals(), context_instance=RequestContext(request))

def loginpage(request):
    return render_to_response('Main/login.html', locals(), context_instance=RequestContext(request))

def login_user(request):
    #if not request.user.is_authenticated():
    context =RequestContext(request)
    if request.method == "POST":
            username = request.POST.get('inputEmail')
            password = request.POST.get('inputPassword')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    expenses = Expense.objects.filter(user=request.user).order_by('-date_created')
                    balances =Balance.objects.filter(user=request.user)
                    return render(request, 'Main/home_page.html',{'expenses':expenses[0:10],'balances':balances})
                else:
                    return render(request,'Main/login.html',{'error_message':'Your account has been disabled'})
            else:
                return render(request,'Main/login.html',{'error_message':'Invalid login'})
    else:
        return render(request,'Main/login.html')




def register_user(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()

        balance = Balance()
        user = User.objects.get(id=user.id)
        balance.user = user
        balance.income = 0
        balance.expense = 0
        balance.total=0
        balance.save()
       # user = authenticate(username=username, password=password)
        #if user is not None:
           # if user.is_active:
                #login(request, user)
               # owners = Owner.objects.filter(user=request.user)
        return render(request, 'Main/login.html',{})
    context = {
        "form": form,
    }
    return render(request,'Main/signup.html', context)

def exp_form(request):
    return render(request, 'Main/exp_form.html',None)
def loan_form(request):
    return render(request, 'Main/loan_pre_form.html',None)


def home_page(request):
    expenses = Expense.objects.filter(user=request.user).order_by('-date_created')
    balances = Balance.objects.filter(user=request.user)

    return render(request, 'Main/home_page.html',{'expenses':expenses[0:10],'balances':balances})

def save(request):

    return render(request, 'Main/home_page.html', {})

def log_out(request):
    logout(request)
    return render(request,'registration/logout.html')

def showtransactions(request):
    if request.method == 'POST':
        x = request.POST['date_in']
        y = request.POST['date_out']
        expenses = Expense.objects.filter(user=request.user).filter(date_created__range=[x,y])
        return render(request, 'Main/transactions.html', {'expenses': expenses})
    else:
        expenses=Expense.objects.filter(user=request.user).order_by('-date_created')
        return render(request,'Main/transactions.html',{'expenses':expenses})





def addexpense(request):
    if request.method == 'POST':
        expenses = Expense()

        user = request.user
        expenses.user = user

        expenses.paid_to = request.POST['expname']
        expenses.source = request.POST['cardtypexp']
        expenses.option = request.POST['types']


        expenses.date_created = request.POST['expdate']
        expenses.tax_details = request.POST['carddet']
        expenses.cost=  request.POST['amount']


        expenses.vat = request.POST['vat_id']
        expenses.ext_ref = request.POST['external_ref']
        expenses.description = request.POST['long_desc']
        if request.FILES['attachment_file']:
            expenses.bill = request.FILES['attachment_file']

        expenses.subcategories = request.POST['sub']
        expenses.is_recurrent = request.POST['is_recurrent']
        if expenses.is_recurrent == True:
            expenses.rec_date = request.POST['expdate']
            #expenses.rec_day = request.POST['rec_day']
            #expenses.rec_month = request.POST['rec_month']
            #expenses.rec_year = request.POST['rec_year']F
        expenses.save()
        x = expenses.cost

        try:
            balance = Balance.objects.filter(user=request.user).get(user_id=request.user.id)

            if expenses.option == 'Income':
                balance.income += int(x)
                balance.total += int(x)
            else:
                balance.expense += int(x)
                balance.total -= int(x)
            balance.save()
        except:
            balance = Balance()
            balance.user = request.user
            if expenses.option == 'Income':
                balance.income = x
                balance.expense = 0
                balance.total = x
                balance.save()
            else:
                balance.expense = x
                balance.income = 0
                balance.total = -int(x)
                balance.save()

        if (request.POST.get("is_recurrent") == "True"):
            print(" \n \n entered iscalendar =tru \n")

            print(" \n \n entered calendar now trying to add event \n \n")
            SCOPES = 'https://www.googleapis.com/auth/calendar'




            flow = flow_from_clientsecrets('D:\client_secrets.json', scope=SCOPES)
            storage = oauth2client.file.Storage('credentials.dat')
            # credentials = storage.get()
            http = httplib2.Http()
            flags = tools.argparser.parse_args(args=[])
            credentials = tools.run_flow(flow, storage, flags)
            # credentials = run(flow, storage, http=http)
            http = credentials.authorize(http)
            CAL = build('calendar', 'v3', http=http)
            dateString = ''
            dateString = request.POST.get('bday')
            dates = dateString[0:4] + dateString[5:7] + dateString[8:10]
            # ((int(request.GET.get('rate')))/100)

            print("\n  calendar was built successfully \n \n")
            GMT_OFF = '+05:30'  # PDT/MST/GMT-7
            EVENT = {
                'summary': 'Expense : ' + request.POST.get('expname') + ' Amount to be paid is ' +request.POST.get('amount') ,
                'start': {'date': request.POST.get('expdate')},
                'end': {'date': request.POST.get('expdate')},
                'recurrence': ['RRULE:FREQ=' + request.POST.get('etype')+';UNTIL='+dates],
            }

            e = CAL.events().insert(calendarId='primary',
                                    sendNotifications=True, body=EVENT).execute()
            print("\n \n event successfuly added \n \n")
            url = 'www.google.com/calendar'
            webbrowser.open_new(url)

    return render(request,'Main/exp_form.html',{})

def delete(request,ex_id):
    try:
        expenses = Expense.objects.filter(user=request.user).get(pk=ex_id)

        balance = Balance.objects.filter(user=request.user).get(user_id=request.user.id)
        x = expenses.cost
        if expenses.option == 'Expense':
            balance.expense -= x
            balance.total += x
        else:
            balance.income -= x
            balance.total -=x

        balance.save()
        expenses.delete()
        return redirect('Main:home_page')
    except:
        lp = LoanPremium.objects.filter(user=request.user).get(pk=ex_id)
        lp.delete()
        return redirect('Main:trans')


def getExpense(request):

    if request.method=='POST':
        x = request.POST['date_in']
        y = request.POST['date_out']
        weatherdata = \
            DataPool(
                series=
                [{'options': {
                    'source': Expense.objects.all().filter(user=request.user).filter(option__exact='Expense').filter(date_created__range=[x,y])},
                    'terms': [
                        {'expense': 'cost'},
                        {'date_expense': 'date_created'},
                    ]},
                    {'options': {

templates/Main/chart.html
{% extends 'Main/base.html' %}
{% block body %}

<head>
    <!-- code to include the highcharts and jQuery libraries goes here -->
    <!-- load_charts filter takes a comma-separated list of id's where -->
    <!-- the charts need to be rendered to                             -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src="http://code.highcharts.com/highcharts.js" type="text/javascript"></script>
    <script src="/highcharts.js" type="text/javascript"></script>


{#    {{ cht1|load_charts:"container3" }}#}
</head>
<body><br><br><br>

    {% load chartit %}

    <div id='container1' class="container col-lg-8 pull-right">{{cht|load_charts:"container1"}}</div>



        <div class="row">
            <div class="col-sm-3 col-xs-12 left-column" > <!-- left column -->
                <div class="container-fluid" style="border: 1px solid black">

                    <div class="row"> <!-- filters -->
                        <div class="filter-well shadow-box col-sm-12 col-xs-10">


<div id="filter-page-header" class="page-header page-header-small page-header-small-pointer">
  <div onclick="showFilters();" class="container-cat-header"><span>&nbsp;<strong>Filter results</strong></span><span id="filter-icon-down" class="glyphicon glyphicon-menu-down visible-xs pull-left"></span></div>

</div>
<div id="filter-contents" class="hidden-xs">
<form method="post" action="{% url 'Main:getExpense' %}">
    {% csrf_token %}
<div class="form-group">
  <div class="input-group">
              <label for="date_in" class="control-label order_by_label_jom">From: &nbsp </label>

    <input class="form-control" type="date" name="date_in" id="date_in" size="16"  value=""  placeholder="From"/>

  </div>
</div>
<div class="form-group">
  <div class="input-group">
              <label for="date_out" class="control-label order_by_label_jom">To:&nbsp &nbsp &nbsp &nbsp</label>

    <input class="form-control " type="date" name="date_out" id="date_out"   value="" placeholder="To"/>
      </div>
</div>


<input type="submit" class="btn btn-info btn-sm"><br><br>
     </form>
    </div>
    </div>
                        </div>
                    </div></div>

     <div class="col-sm-3 col-sm-5"><br>
                                    <div class="col-sm">&nbsp&nbsp</div>
                                    <a type="button" class="btn btn-success pull-right" href="{% url 'Main:getExpense2' %}">Next</a>

                                </div>

    <div class="container-fluid" >


{% endblock %}
<</body>

templates/Main/chart2.html
{% extends 'Main/base.html' %}
{% block body %}

<head>
    <!-- code to include the highcharts and jQuery libraries goes here -->
    <!-- load_charts filter takes a comma-separated list of id's where -->
    <!-- the charts need to be rendered to                             -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src="http://code.highcharts.com/highcharts.js" type="text/javascript"></script>
    <script src="/highcharts.js" type="text/javascript"></script>


{#    {{ cht1|load_charts:"container3" }}#}
</head>
<body><br><br><br>

    {% load chartit %}

    <div id='container1' class="container col-lg-8 pull-right">{{cht|load_charts:"container1"}}</div>



        <div class="row">
            <div class="col-sm-3 col-xs-12 left-column" > <!-- left column -->
                <div class="container-fluid" style="border: 1px solid black">

                    <div class="row"> <!-- filters -->
                        <div class="filter-well shadow-box col-sm-12 col-xs-10">


<div id="filter-page-header" class="page-header page-header-small page-header-small-pointer">
  <div onclick="showFilters();" class="container-cat-header"><span>&nbsp;<strong>Filter results</strong></span><span id="filter-icon-down" class="glyphicon glyphicon-menu-down visible-xs pull-left"></span></div>

</div>
<div id="filter-contents" class="hidden-xs">
<form method="post" action="{% url 'Main:getExpense2' %}">
    {% csrf_token %}
<div class="form-group">
  <div class="input-group">
              <label for="date_in" class="control-label order_by_label_jom">From: &nbsp </label>

    <input class="form-control" type="date" name="date_in" id="date_in" size="16"  value=""  placeholder="From"/>

  </div>
</div>
<div class="form-group">
  <div class="input-group">
              <label for="date_out" class="control-label order_by_label_jom">To:&nbsp &nbsp &nbsp &nbsp</label>

    <input class="form-control " type="date" name="date_out" id="date_out"   value="" placeholder="To"/>
      </div>
</div>


<input type="submit" class="btn btn-info btn-sm"><br><br>
     </form>
    </div>
    </div>
                        </div>
                    </div></div>

     <div class="col-sm-3 col-sm-5"><br>
                                    <div class="col-sm">&nbsp&nbsp</div>
                                    <a type="button" class="btn btn-success pull-right" href="{% url 'Main:getExpense' %}">Next</a>

                                </div>

    <div class="container-fluid" >


{% endblock %}
<</body>

templates/Main/home_page.html
{% extends 'Main/base.html' %}


{% block body %}
 <head><style>
     @charset "utf-8";
/* CSS Document */

body{
    background-color: lightgrey;
}
tr.linefinances1 td, tr.linefinances2 td{
	padding:5px;
	height:16px;

	background: -moz-linear-gradient(top,  #eeeeee 0%, #f8f8f8 100%); /* FF3.6+ */

	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#eeeeee), color-stop(100%,#f8f8f8)); /* Chrome,Safari4+ */

	background: -webkit-linear-gradient(top,  #eeeeee 0%,#f8f8f8 100%); /* Chrome10+,Safari5.1+ */

	background: -o-linear-gradient(top,  #eeeeee 0%,#f8f8f8 100%); /* Opera 11.10+ */

	background: -ms-linear-gradient(top,  #eeeeee 0%,#f8f8f8 100%); /* IE10+ */

	background: linear-gradient(to bottom,  #eeeeee 0%,#f8f8f8 100%); /* W3C */

	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#eeeeee', endColorstr='#f8f8f8',GradientType=0 ); /* IE6-9 */

}

tr.footfinances td{

	background-color:#EEEEEE;
	border-top:2px solid #CCC;
}

tr.headerfinances td{
	padding:5px;
	background-color:#EEEEEE;
	border-bottom:2px solid #CCC;
}




.artist_data h3{
	font-size: 16px;
    font-weight: normal;
    line-height: 100%;
    margin: 0 0 5px;
    padding: 0;

	border-bottom: 1px solid #ECECEC;

}







.radio.btn-group input[type=radio] {
display: none;
}




.resume-number {
	padding: 10px;
	font-size: 18px;
	font-weight: 300;
	line-height: 18px;
	color: #FFFFFF;
	text-align: right;
	padding-top: 15px;
}

.resume-income {
	background: #5cb85c;
}

.resume-outcome {
	background: #d9534f;
}

.resume-balance {
	background: #eee;
}



.resume-balance-zero {
	color: #777;
}

.resume-title {
	padding-top: 5px;
	font-size: 80%;
	display: block;
}

.summary-item {
	margin-bottom: 10px;
}

.summary-well {
	margin-bottom: 20px;
}

.summary-number {
	white-space: nowrap;
	font-size: 25px;
}



.input-typeahead > span {
	height: 30px !important;
}

.input-typeahead span input {
	border-radius: 4px !important;
}

/*http://www.materialup.com/posts/material-design-box-shadows*/
.shadow-box{
	//background: #fff;
	border-radius: 2px;

	box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
	transition: all 0.2s ease-in-out;
}


.noshadow-box {
	border-radius: 2px;
	transition: all 0.2s ease-in-out;
}


.highlight_item td {

  	background-color: #d9edf7;
}

.highlight_item_fade td{
	transition: background-color 2s ease;
	background-color: transparent;
}


 </style></head> <body>
   <br><br>{% if balances %}{% for balance in balances %}
        <div style="text-align: center;">  <h1 class="page-header">DashBoard</h1></div>

                    <div class="row"> <!-- summary -->
                        <div class="summary-well container-fluid">
<div class="row" style="margin-left:270px;">
    <div class="col-sm-3 hidden-xs summary-item noshadow-box resume-number resume-income">
        <span class="summary-number" id="summary_income_num">{{ balance.income}}</span>
        <span class="resume-title">Income</span>
    </div>


    <div class="col-sm-3 hidden-xs summary-item noshadow-box resume-number resume-outcome">
        <span class="summary-number" id="summary_outcome_num">{{ balance.expense }}</span>
        <span class="resume-title">Outcome</span>
    </div>

    <div id="resume-background-balance" class="col-sm-3 summary-item noshadow-box resume-number resume-balance resume-balance-zero">
        <span class="summary-number" id="summary_balance_num">{{ balance.total }}</span>
        <span class="resume-title">Balance</span>
    </div>

</div>
</div>
{% endfor %}
   {% else %}
     <div style="text-align: center;">  <h1 class="page-header">DashBoard</h1></div>

                    <div class="row"> <!-- summary -->
                        <div class="summary-well container-fluid">
<div class="row" style="margin-left:270px;">
    <div class="col-sm-3 hidden-xs summary-item noshadow-box resume-number resume-income">
        <span class="summary-number" id="summary_income_num">0</span>
        <span class="resume-title">Income</span>
    </div>


    <div class="col-sm-3 hidden-xs summary-item noshadow-box resume-number resume-outcome">
        <span class="summary-number" id="summary_outcome_num">0</span>
        <span class="resume-title">Outcome</span>
    </div>

    <div id="resume-background-balance" class="col-sm-3 summary-item noshadow-box resume-number resume-balance resume-balance-zero">
        <span class="summary-number" id="summary_balance_num">0</span>
        <span class="resume-title">Balance</span>
    </div>

</div>
</div>
                    {% endif %}

                    </div>
          <div class="row ">
		  <div class="col-sm-2"></div>
            <div class="col-sm-2">
                <a href="{% url "Main:exp_form" %}">
               <img src="../../static/Main/Images/add.jpg" width="200" height="200" class="img-circle" alt="Generic placeholder thumbnail"></a>
              <div style="text-align:center;"><h4>Add Expense/Income</h4></div>
              
            </div>
            <div class="col-sm-2 ">
                <a href="{% url 'Main:loan_form' %}">
              <img src="../../static/Main/Images/loan.jpg" width="200" height="200" class="img-circle" alt="Generic placeholder thumbnail"></a>
             <div style="text-align:center;"><h4>Loans and Premiums</h4></div>
             
            </div>
            <div class="col-sm-2">
                <a href="{% url 'Main:getExpense' %}">
              <img src="../../static/Main/Images/graph.jpg" width="200" height="200" class="img-circle"alt="Generic placeholder thumbnail"></a>
             <div style="text-align: center;"><h4>Reports</h4></div>
              
            </div>
            <div class="col-sm-2">
                <a href="{% url 'Main:profile' %}">
              <img src="../../static/Main/Images/profile.png" width="200" height="200" class="img-circle" alt="Generic placeholder thumbnail"></a>
             <div style="text-align: center;"> <h4>Profile</h4></div>
              
            </div>
			<div class="col-sm-2"></div>
          </div>

		  
<br>		  
<div class="row">
<div class="col-sm-2"></div>
<div class="col-sm-8">
         <div style="text-align: center;"> <h2 class="sub-header">Recent Transactions</h2></div>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Sr No.</th>
                  <th>Name</th>
                  <th>Category/Source</th>
                  <th>Amount</th>
                  <th>Date</th>
                    <th> Details </th>
                </tr>
              </thead>
              <tbody>
                {% include 'Main/table_template_dash.html' %}
              </tbody>
            </table>
          </div>

    <a type="button" class="btn btn-success" href="{% url 'Main:transactions' %}" >Expenses/Incomes Records</a>
    <a type="button" class="btn btn-success" href="{% url 'Main:trans' %}" >Loan/Premium Records</a>
        </div>
      </div>
    </div>
	</div>
	<div class="col-sm-2"></div>
	</div>
    </body>

{% endblock %}

templates/Main/signup.html
{% extends 'Main/base_visitor.html' %}

{% block body %}
<body>
<br><br><br>
<div class="bs-example">
    <h1>Sign Up</h1>
      {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
        {% endif %}
<form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'Main/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <input type="submit" name="Submit" class="btn btn-success"/>
                            </div>
                        </div>
                    </form>
</div>
</body>
{%  endblock %}