Expenze/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Main/',include('Main.urls')),
    url(r'^accounts/',include('registration.backends.hmac.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/urls.py
from django.conf.urls import url
from django.contrib import admin
from Main import views
app_name ='Main'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^home/$',views.login_user,name='home'),
    url(r'^register_user/$',views.register_user,name='register_user'),
    url(r'^home_page/$',views.home_page,name='home_page'),
    url(r'^save/$',views.save,name='save'),
    url(r'^loginpage/$',views.loginpage,name='loginpage'),
    url(r'^exp_form/$',views.exp_form,name='exp_form'),
    url(r'^logout/$',views.log_out,name='logout'),
    url(r'^addexpense/$',views.addexpense,name='addexpense'),
    url(r'^chart/$',views.getExpense,name='getExpense'),
    url(r'^delete/(?P<ex_id>\d+)$',views.delete,name='delete'),
    url(r'^transactions/$',views.showtransactions,name='transactions'),
    url(r'^addloanpremium/$', views.addloanpremium, name='addloanpremium'),
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^editprofile/$', views.editprofile, name='editprofile'),
    url(r'^update/(?P<ex_id>\d+)$',views.update,name='update'),
    url(r'^lptransaction/$', views.transactions, name='trans'),
    url(r'^lpfilter/$', views.lpfilter, name='lpfilter'),
    url(r'^chart2/$',views.getExpense2,name='getExpense2'),
    url(r'^loan_form/$',views.loan_form,name='loan_form'),
    url(r'^delete_user/(?P<u_id>\d+)$', views.delete_user, name='delete_user'),
    url(r'^pdf',views.pdf,name="pdf"),

]

templates/base_visitor.html
<!DOCTYPE html>
<html lang="en">

<head>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<link href="data:image/x-icon;base64,AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAA4ujYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAERERAAAREREQAAAAAAAAARAAAAAAAAABEAAAAAAAAAEQABEAABEAAREREQAAEQABEAAAAAAAAAEQAAAAAAAAARAAAAAAAAABEAARAAAREREQABEAABEAARAAAAAAAAABEAAAAAAAAAEQAAAAAAAAAREREQAAERERERERAAARERH8PwAAgAEAAIABAACAAQAAjDEAAPwxAACAAQAAgAEAAIABAACMPwAAjDEAAIABAACAAQAAgAEAAPw/AAD8PwAA" rel="icon" type="image/x-icon" />




</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="{% url 'Main:index' %}">Expenze Manager</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-left">
				<li>
                    <a href="#hme">Home</a>
                    </li>
                    <li>
                        <a href="#about">About</a>
                    </li>
                    <li>
                        <a href="#services">Features</a>
                    </li>
                    <li>
                        <a href="#contact">Contact</a>
                    </li></ul>
			<ul class="nav navbar-nav navbar-right">
			<li>
                    <a href="{% url 'registration_register' %}">Register</a>
                    </li>
					<li>
                    <a href="{% url 'auth_login' %}">login</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
{% block body %}
{% endblock %}

templates/form-template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<br><br>
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" id="fields"  class="sr-only">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}
</body>
</html>